services:
  - name: chatbot-furia
    type: web
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: API_KEY
        value: "AIzaSyDAdVRI8x6tmdmYjcKwEJQ1H-5bPtehVHY"